package test_models.generator_demo.test1;

/*Generated by MPS */

import javax.swing.JFrame;
import java.awt.Container;
import java.awt.Component;
import javax.swing.JButton;
import javax.swing.JLabel;

public class Application {
  public static void main(String[] args) {
    JFrame frame = new JFrame("Generator");
    frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    frame.pack();
    frame.setLocationRelativeTo(null);
    frame.setVisible(true);
    Container container = frame.getContentPane();
    addContent(container);
  }

  public static void addContent(Container container) {
    container.add(createComponent_a());
    container.add(createComponent_a_0());
  }

  public static Component createComponent_a() {
    JButton component = new JButton();
    component.setText("Hello");
    return component;
  }
  public static Component createComponent_a_0() {
    JLabel component = new JLabel();
    component.setText("Luka");
    return component;
  }
}
