package test_models.generator_demo.test1;

/*Generated by MPS */

import java.awt.Container;
import javax.swing.JFrame;
import java.awt.Component;
import javax.swing.JButton;
import javax.swing.JLabel;

public class Application {
  public static void main(String[] args) {
    Container container = container();
    addContent(container);
  }


  public static Container container() {
    JFrame frame = new JFrame("Hello");
    frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    frame.pack();
    frame.setLocationRelativeTo(null);
    frame.setVisible(true);
    Container container = frame.getContentPane();
    return container;
  }

  public static void addContent(Container container) {
    container.add(createComponent_a0());
    container.add(createComponent_b0());
  }

  public static Component createComponent_a0() {
    JButton component = new JButton();
    component.setText("Confirm");
    return component;
  }
  public static Component createComponent_b0() {
    JLabel component = new JLabel();
    component.setText("Name:");
    return component;
  }
}
